name: Unlighthouse and Dastardly

on:
  workflow_dispatch:
  push:
    branches:
      - main  # Trigger on push to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull request targeting the main branch

permissions:
  contents: read
  checks: write
  id-token: write

jobs:
  demo:
    runs-on: ubuntu-latest
    env:
      SITE_URL: yusufasik.com
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Dependencies
        run: npm install -g @unlighthouse/cli puppeteer netlify-cli

      - name: Unlighthouse Scan
        run: unlighthouse-ci --site ${{ env.SITE_URL }} --debug --build-static --throttle --no-cache --samples 3

      - name: Dastardly Scan
        continue-on-error: true 
        uses: PortSwigger/dastardly-github-action@main
        with:
          target-url: ${{ env.SITE_URL }}
          output-filename: dastardly-report.xml

      - name: Upload security scan results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: dastardly-reports
          path: dastardly-report.xml

      - name: Deploy
        uses: netlify/actions/cli@master
        with:
         args: deploy --dir=.unlighthouse --prod --message="New Release Deploy from GitHub Actions"
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
