name: Assertions and static report

on:
  workflow_dispatch:

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Dependencies
        run: npm install -g @unlighthouse/cli puppeteer netlify-cli

      - name: Unlighthouse assertions and client
        run: unlighthouse-ci --site yusufasik.com --build-static --debug --throttle --no-cache --samples 3

      - name: Deploy to Netlify
        run: |
          npx netlify-cli deploy --dir=.unlighthouse --prod --message="New Release Deploy from GitHub Actions" --auth $NETLIFY_AUTH_TOKEN --site $NETLIFY_SITE_ID
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
