name: Assertions and static report

on:
  workflow_dispatch:

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Dependencies
        run: npm install -g @unlighthouse/cli puppeteer netlify-cli

      - name: Unlighthouse assertions and client
        run: unlighthouse-ci --site yusufasik.com --debug --build-static

      - name: Deploy to Netlify
        run: |
         npx netlify-cli link --id ${{ secrets.NETLIFY_SITE_ID }} --auth ${{ secrets.NETLIFY_AUTH_TOKEN }}
         npx netlify-cli deploy \
         --dir=.unlighthouse \
         --prod \
         --auth=${{ secrets.NETLIFY_AUTH_TOKEN }} \
         --json
        env:
         CI: true
