name: Dastardly Report

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

permissions:
  contents: read
  checks: write
  id-token: write

jobs:
  dastardly:
    name: Dastardly Scan
    runs-on: ubuntu-latest
    env:
      SITE_URL: https://yusufasik.com
    steps:
      - uses: actions/checkout@v4
      - name: Dastardly Scan
        continue-on-error: true
        uses: PortSwigger/dastardly-github-action@main
        with:
          target-url: ${{ env.SITE_URL }}
          output-filename: dastardly-report.xml
          
      - name: Upload security scan results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: dastardly-reports
          path: dastardly-report.xml
