name: Unlighthouse CI Report

on:
  workflow_dispatch:

jobs:
  UnlighthouseCI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install @unlighthouse/cli puppeteer

      - name: Run Unlighthouse
        run: npx unlighthouse-ci --site yusufasik.com --debug --build-static --throttle --no-cache --samples 3
        
      - name: Deploy
        uses: netlify/actions/cli@master
        with:
          args: deploy --dir=.unlighthouse --prod --message="New Release Deploy from GitHub Actions"
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
